export const siteConfig = {
  name: 'Jua',
  title: 'Jua — Go + React Full-Stack Framework',
  description:
    'The full-stack meta-framework that combines Go, React, and a Filament-like admin panel. Scaffold entire projects, generate full-stack resources, and ship fast.',
  url: 'https://juaframework.dev',
  ogImage: 'https://juaframework.dev/opengraph-image.png',
  creator: 'katuramuh',
  author: 'Katuramu',
  github: 'https://github.com/katuramuh/jua',
  youtube: 'https://www.youtube.com/@JuaFramework',
  linkedin: 'https://www.linkedin.com/company/jua-framework',
  website: 'https://juaframework.dev',
  keywords: [
    'Go framework',
    'React framework',
    'full-stack framework',
    'Jua',
    'Gin',
    'GORM',
    'Next.js',
    'admin panel',
    'code generator',
    'monorepo',
    'Go + React',
    'TypeScript',
    'Tailwind CSS',
    'shadcn/ui',
    'REST API',
    'RBAC',
    'scaffolding',
    'full-stack Go',
    'Go web framework',
    'React admin dashboard',
  ],
}
