package scaffold

import (
	"fmt"
	"path/filepath"
)

func writeDesktopFrontendLayoutFiles(root string, opts DesktopOptions) error {
	files := map[string]string{
		filepath.Join(root, "frontend", "src", "components", "layout", "title-bar.tsx"):       desktopTitleBar(),
		filepath.Join(root, "frontend", "src", "components", "layout", "sidebar.tsx"):          desktopSidebar(),
		filepath.Join(root, "frontend", "src", "components", "layout", "draggable-window.tsx"): desktopDraggableWindow(),
		filepath.Join(root, "frontend", "src", "routes", "_layout.tsx"):                        desktopLayoutRoute(),
	}

	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}

	return nil
}

func desktopTitleBar() string {
	return `import { useState } from "react";
import { Minus, Square, X, Sun, Moon } from "lucide-react";
import { useTheme } from "../../hooks/use-theme";

// @ts-ignore - auto-generated by wails
import { MinimiseWindow, ToggleMaximise, CloseApp } from "../../../wailsjs/go/main/App";

export default function TitleBar() {
  const { theme, toggleTheme } = useTheme();

  return (
    <div className="flex items-center justify-between h-9 bg-background border-b border-border select-none">
      <div
        className="flex-1 flex items-center h-full px-3"
        style={{ "--wails-draggable": "drag" } as React.CSSProperties}
      >
        <span className="text-sm font-semibold text-foreground">Jua Desktop</span>
      </div>

      <div className="flex items-center">
        <button
          onClick={toggleTheme}
          className="h-9 w-10 flex items-center justify-center text-text-secondary hover:bg-bg-hover transition-colors"
        >
          {theme === "dark" ? <Sun size={14} /> : <Moon size={14} />}
        </button>
        <button
          onClick={() => MinimiseWindow()}
          className="h-9 w-10 flex items-center justify-center text-text-secondary hover:bg-bg-hover transition-colors"
        >
          <Minus size={14} />
        </button>
        <button
          onClick={() => ToggleMaximise()}
          className="h-9 w-10 flex items-center justify-center text-text-secondary hover:bg-bg-hover transition-colors"
        >
          <Square size={12} />
        </button>
        <button
          onClick={() => CloseApp()}
          className="h-9 w-10 flex items-center justify-center text-text-secondary hover:bg-danger hover:text-white transition-colors"
        >
          <X size={14} />
        </button>
      </div>
    </div>
  );
}
`
}

func desktopSidebar() string {
	return `import { useState, useEffect } from "react";
import { useLocation, useNavigate, Link } from "@tanstack/react-router";
import {
  LayoutDashboard, FileText, Users, ChevronLeft, ChevronRight, LogOut,
  // jua:nav-icons
} from "lucide-react";
import { useAuth } from "../../hooks/use-auth";

const navItems = [
  { label: "Dashboard", path: "/", icon: LayoutDashboard },
  { label: "Blogs", path: "/blogs", icon: FileText },
  { label: "Contacts", path: "/contacts", icon: Users },
  // jua:nav
];

export default function Sidebar() {
  const { user, logout } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [collapsed, setCollapsed] = useState(() => {
    return localStorage.getItem("jua-sidebar") === "collapsed";
  });

  useEffect(() => {
    localStorage.setItem("jua-sidebar", collapsed ? "collapsed" : "expanded");
  }, [collapsed]);

  const handleLogout = () => {
    logout();
    navigate({ to: "/login" });
  };

  const isActive = (path: string) => {
    if (path === "/") return location.pathname === "/";
    return location.pathname.startsWith(path);
  };

  return (
    <div className={"flex flex-col h-full border-r border-border bg-background transition-all duration-200 " + (collapsed ? "w-16" : "w-56")}>
      <nav className="flex-1 py-3 space-y-1 px-2">
        {navItems.map((item) => {
          const Icon = item.icon;
          const active = isActive(item.path);
          return (
            <Link
              key={item.path}
              to={item.path}
              className={"flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition-colors " +
                (active
                  ? "bg-accent/10 text-accent font-medium"
                  : "text-text-secondary hover:bg-bg-hover hover:text-foreground"
                )
              }
            >
              <Icon size={18} />
              {!collapsed && <span>{item.label}</span>}
            </Link>
          );
        })}
      </nav>

      <div className="border-t border-border p-2 space-y-1">
        {user && !collapsed && (
          <div className="px-3 py-2">
            <div className="text-sm font-medium text-foreground truncate">{user.name}</div>
            <div className="text-xs text-text-muted truncate">{user.email}</div>
            <span className="inline-block mt-1 px-2 py-0.5 text-xs rounded bg-accent/10 text-accent">{user.role}</span>
          </div>
        )}
        <button
          onClick={handleLogout}
          className="flex items-center gap-3 w-full px-3 py-2 rounded-lg text-sm text-text-secondary hover:bg-bg-hover hover:text-danger transition-colors"
        >
          <LogOut size={18} />
          {!collapsed && <span>Sign Out</span>}
        </button>
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="flex items-center justify-center w-full px-3 py-2 rounded-lg text-text-muted hover:bg-bg-hover transition-colors"
        >
          {collapsed ? <ChevronRight size={16} /> : <ChevronLeft size={16} />}
        </button>
      </div>
    </div>
  );
}
`
}

func desktopLayoutRoute() string {
	return `import { createFileRoute, Outlet, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { useAuth } from "../hooks/use-auth";
import TitleBar from "../components/layout/title-bar";
import Sidebar from "../components/layout/sidebar";

export const Route = createFileRoute("/_layout")({
  component: LayoutComponent,
});

function LayoutComponent() {
  const { isAuthenticated, isLoading } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      navigate({ to: "/login" });
    }
  }, [isAuthenticated, isLoading, navigate]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-screen bg-background">
        <div className="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!isAuthenticated) return null;

  return (
    <div className="flex flex-col h-screen bg-background overflow-hidden">
      <TitleBar />
      <div className="flex flex-1 overflow-hidden">
        <Sidebar />
        <main className="flex-1 overflow-auto p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
`
}

func desktopDraggableWindow() string {
	return `import { useState, useRef, useCallback, useEffect } from "react";
import { X, GripHorizontal } from "lucide-react";

interface DraggableWindowProps {
  title: string;
  isOpen: boolean;
  onClose: () => void;
  children: React.ReactNode;
  defaultPosition?: { x: number; y: number };
  width?: number;
}

export default function DraggableWindow({
  title,
  isOpen,
  onClose,
  children,
  defaultPosition = { x: 100, y: 100 },
  width = 400,
}: DraggableWindowProps) {
  const [position, setPosition] = useState(defaultPosition);
  const [isDragging, setIsDragging] = useState(false);
  const dragOffset = useRef({ x: 0, y: 0 });

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    setIsDragging(true);
    dragOffset.current = {
      x: e.clientX - position.x,
      y: e.clientY - position.y,
    };
  }, [position]);

  useEffect(() => {
    if (!isDragging) return;

    const handleMouseMove = (e: MouseEvent) => {
      setPosition({
        x: e.clientX - dragOffset.current.x,
        y: e.clientY - dragOffset.current.y,
      });
    };

    const handleMouseUp = () => setIsDragging(false);

    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);
    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [isDragging]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed z-50 rounded-xl border border-border bg-bg-elevated shadow-2xl shadow-black/30 overflow-hidden"
      style={{ left: position.x, top: position.y, width }}
    >
      <div
        className="flex items-center justify-between px-4 py-2 border-b border-border cursor-move select-none bg-background"
        onMouseDown={handleMouseDown}
      >
        <div className="flex items-center gap-2 text-sm font-medium text-foreground">
          <GripHorizontal size={14} className="text-text-muted" />
          {title}
        </div>
        <button
          onClick={onClose}
          className="p-1 rounded hover:bg-bg-hover text-text-muted hover:text-foreground transition-colors"
        >
          <X size={14} />
        </button>
      </div>
      <div className="p-4">{children}</div>
    </div>
  );
}
`
}
