package scaffold

import (
	"fmt"
	"path/filepath"
	"strings"
)

// WriteAgentsMD generates an AGENTS.md file at the project root.
// This file gives AI coding agents (Claude Code, Cursor, Copilot, etc.)
// full context about the generated project's architecture, conventions, and tasks.
func WriteAgentsMD(root string, opts Options) error {
	opts.Normalize()
	path := filepath.Join(root, "AGENTS.md")
	content := buildAgentsMD(opts)
	if err := writeFile(path, content); err != nil {
		return fmt.Errorf("writing AGENTS.md: %w", err)
	}
	return nil
}

func buildAgentsMD(opts Options) string {
	name := strings.Title(strings.ReplaceAll(opts.ProjectName, "-", " "))
	module := opts.Module()

	var sb strings.Builder

	sb.WriteString("# AGENTS.md — " + name + "\n\n")
	sb.WriteString("> This file is auto-generated by `jua generate agents`.\n")
	sb.WriteString("> It gives AI coding agents full context about this project. Keep it up to date.\n\n")
	sb.WriteString("---\n\n")

	sb.WriteString("## What Is This Project?\n\n")
	sb.WriteString("**" + name + "** is a full-stack application built with the [Jua framework](https://github.com/katuramuh/jua).\n\n")
	sb.WriteString("- **Backend:** Go (Gin + GORM), module path `" + module + "`\n")
	if opts.ShouldIncludeWeb() {
		sb.WriteString("- **Frontend:** Next.js 14+ (App Router, TypeScript, Tailwind CSS + shadcn/ui)\n")
	}
	if opts.ShouldIncludeAdmin() {
		sb.WriteString("- **Admin Panel:** Next.js admin with resource-based CRUD, dark theme\n")
	}
	sb.WriteString("- **Database:** PostgreSQL (production), SQLite (testing)\n")
	sb.WriteString("- **Cache/Queue:** Redis + asynq\n")
	sb.WriteString("- **File Storage:** S3-compatible (MinIO for local dev)\n\n")

	sb.WriteString("---\n\n")

	sb.WriteString("## Architecture\n\n")
	sb.WriteString("```\n")
	if opts.Architecture == ArchSingle {
		sb.WriteString(name + "/\n")
		sb.WriteString("├── cmd/server/        # Go entrypoint\n")
		sb.WriteString("├── cmd/migrate/       # DB migration runner\n")
		sb.WriteString("├── internal/\n")
		sb.WriteString("│   ├── config/        # App config (env vars)\n")
		sb.WriteString("│   ├── database/      # GORM setup\n")
		sb.WriteString("│   ├── models/        # GORM models\n")
		sb.WriteString("│   ├── handlers/      # HTTP handlers (thin — call services)\n")
		sb.WriteString("│   ├── services/      # Business logic\n")
		sb.WriteString("│   ├── middleware/    # Gin middleware (auth, CORS, logger)\n")
		sb.WriteString("│   ├── routes/        # Route registration\n")
		sb.WriteString("│   ├── providers/     # SMS, Payment, WhatsApp, Email, Push, USSD\n")
		sb.WriteString("│   ├── tenancy/       # Multi-tenancy (Tenant model + scopes)\n")
		sb.WriteString("│   ├── auth/phone/    # Phone OTP authentication\n")
		sb.WriteString("│   ├── ussd/          # USSD engine (App, Router, Flow)\n")
		sb.WriteString("│   ├── webhooks/      # Webhook system (dispatcher, delivery log)\n")
		sb.WriteString("│   ├── billing/       # Billing (Plan, Subscription, Invoice)\n")
		sb.WriteString("│   ├── cache/         # Redis cache service\n")
		sb.WriteString("│   ├── storage/       # S3 file storage\n")
		sb.WriteString("│   ├── mail/          # Email service + templates\n")
		sb.WriteString("│   ├── jobs/          # asynq background workers\n")
		sb.WriteString("│   ├── cron/          # asynq cron scheduler\n")
		sb.WriteString("│   └── ai/            # Claude + OpenAI integration\n")
		sb.WriteString("└── frontend/          # React SPA (Vite + TanStack Router)\n")
	} else {
		sb.WriteString(opts.ProjectName + "/\n")
		sb.WriteString("├── apps/\n")
		sb.WriteString("│   ├── api/           # Go backend\n")
		sb.WriteString("│   │   ├── cmd/server/\n")
		sb.WriteString("│   │   └── internal/\n")
		sb.WriteString("│   │       ├── config/\n")
		sb.WriteString("│   │       ├── database/\n")
		sb.WriteString("│   │       ├── models/\n")
		sb.WriteString("│   │       ├── handlers/\n")
		sb.WriteString("│   │       ├── services/\n")
		sb.WriteString("│   │       ├── middleware/\n")
		sb.WriteString("│   │       ├── routes/\n")
		sb.WriteString("│   │       ├── providers/     # SMS, Payment, WhatsApp, Email, Push, USSD\n")
		sb.WriteString("│   │       ├── tenancy/       # Multi-tenancy\n")
		sb.WriteString("│   │       ├── auth/phone/    # Phone OTP auth\n")
		sb.WriteString("│   │       ├── ussd/          # USSD engine\n")
		sb.WriteString("│   │       ├── webhooks/      # Webhook system\n")
		sb.WriteString("│   │       ├── billing/       # Billing system\n")
		sb.WriteString("│   │       ├── cache/\n")
		sb.WriteString("│   │       ├── storage/\n")
		sb.WriteString("│   │       ├── mail/\n")
		sb.WriteString("│   │       ├── jobs/\n")
		sb.WriteString("│   │       ├── cron/\n")
		sb.WriteString("│   │       └── ai/\n")
		if opts.ShouldIncludeWeb() {
			sb.WriteString("│   ├── web/           # Next.js web app\n")
		}
		if opts.ShouldIncludeAdmin() {
			sb.WriteString("│   └── admin/         # Next.js admin panel\n")
		}
		sb.WriteString("└── packages/\n")
		sb.WriteString("    └── shared/        # Zod schemas + TypeScript types\n")
	}
	sb.WriteString("```\n\n")

	sb.WriteString("---\n\n")

	sb.WriteString("## Coding Rules — MUST FOLLOW\n\n")
	sb.WriteString("### Go (Backend)\n\n")
	sb.WriteString("- **Handlers are thin.** All business logic lives in `internal/services/`. Handlers call services.\n")
	sb.WriteString("- **Every error must be handled.** Never use `_` to discard errors.\n")
	sb.WriteString("- **Use `fmt.Errorf(\"context: %w\", err)`** for error wrapping.\n")
	sb.WriteString("- **Struct tags are required:** `gorm:\"...\"`, `json:\"...\"`, `binding:\"...\"` on every model field.\n")
	sb.WriteString("- **API response format** — always use this structure:\n")
	sb.WriteString("  - Success: `{\"data\": ..., \"message\": \"...\"}`\n")
	sb.WriteString("  - Error: `{\"error\": {\"code\": \"SCREAMING_SNAKE\", \"message\": \"human string\"}}`\n")
	sb.WriteString("  - List: `{\"data\": [...], \"meta\": {\"total\", \"page\", \"page_size\", \"pages\"}}`\n")
	sb.WriteString("- **No external packages** in handlers/services unless already in `go.mod`.\n\n")

	if opts.ShouldIncludeFrontend() {
		sb.WriteString("### TypeScript/React (Frontend)\n\n")
		sb.WriteString("- **Functional components only.** No class components.\n")
		sb.WriteString("- **All data fetching via React Query.** No raw `fetch` in components.\n")
		sb.WriteString("- **Validate API inputs with Zod.** Types come from `packages/shared`.\n")
		sb.WriteString("- **No `any` types.** Define proper interfaces.\n")
		sb.WriteString("- **Tailwind + shadcn/ui only.** No custom CSS files.\n")
		sb.WriteString("- **App Router only.** Never use Pages Router.\n\n")
	}

	sb.WriteString("### Design System\n\n")
	sb.WriteString("```css\n")
	sb.WriteString("--bg-primary:    #0a0a0f\n")
	sb.WriteString("--bg-secondary:  #111118\n")
	sb.WriteString("--bg-elevated:   #22222e\n")
	sb.WriteString("--border:        #2a2a3a\n")
	sb.WriteString("--text-primary:  #e8e8f0\n")
	sb.WriteString("--text-secondary:#9090a8\n")
	sb.WriteString("--accent:        #6c5ce7   /* Jua purple */\n")
	sb.WriteString("--success:       #00b894\n")
	sb.WriteString("--danger:        #ff6b6b\n")
	sb.WriteString("```\n\n")
	sb.WriteString("Fonts: `Onest` (UI) + `JetBrains Mono` (code). Dark mode is the default and required.\n\n")

	sb.WriteString("---\n\n")

	sb.WriteString("## Key Packages & What They Do\n\n")
	sb.WriteString("| Package | Purpose |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `internal/providers/sms` | SMS via Africa's Talking, Relworx, Twilio, Vonage |\n")
	sb.WriteString("| `internal/providers/payment` | Mobile money + cards (MTN MoMo, Airtel, Flutterwave, Paystack, Stripe, PawaPay) |\n")
	sb.WriteString("| `internal/providers/whatsapp` | WhatsApp via Meta Cloud API, AT, Twilio |\n")
	sb.WriteString("| `internal/providers/email` | Email via Resend or SMTP |\n")
	sb.WriteString("| `internal/providers/push` | Push notifications via FCM or OneSignal |\n")
	sb.WriteString("| `internal/providers/ussd` | USSD via Africa's Talking or Yo Uganda |\n")
	sb.WriteString("| `internal/tenancy` | Multi-tenancy (subdomain/header resolution, GORM scopes) |\n")
	sb.WriteString("| `internal/auth/phone` | Phone OTP authentication (6-digit, bcrypt, rate-limited) |\n")
	sb.WriteString("| `internal/ussd` | USSD engine (App, Router, Flow state machine) |\n")
	sb.WriteString("| `internal/webhooks` | Webhook delivery with HMAC signing + exponential backoff retries |\n")
	sb.WriteString("| `internal/billing` | Plan/Subscription/Invoice management |\n")
	sb.WriteString("| `internal/cache` | Redis cache service |\n")
	sb.WriteString("| `internal/storage` | S3/MinIO file uploads |\n")
	sb.WriteString("| `internal/jobs` | asynq background job workers |\n")
	sb.WriteString("| `internal/cron` | asynq cron scheduler |\n")
	sb.WriteString("| `internal/ai` | Claude + OpenAI integration with streaming |\n\n")

	sb.WriteString("---\n\n")

	sb.WriteString("## Switching Providers\n\n")
	sb.WriteString("All providers are controlled by environment variables — no code changes needed:\n\n")
	sb.WriteString("```env\n")
	sb.WriteString("SMS_PROVIDER=africastalking       # africastalking | relworx | esmsafrica | twilio | vonage\n")
	sb.WriteString("PAYMENT_PROVIDER=mtn              # mtn | airtel | flutterwave | paystack | stripe | pawapay\n")
	sb.WriteString("WHATSAPP_PROVIDER=meta            # meta | africastalking | twilio\n")
	sb.WriteString("EMAIL_PROVIDER=resend             # resend | smtp\n")
	sb.WriteString("PUSH_PROVIDER=fcm                 # fcm | onesignal\n")
	sb.WriteString("USSD_PROVIDER=africastalking      # africastalking | yo\n")
	sb.WriteString("```\n\n")

	sb.WriteString("---\n\n")

	sb.WriteString("## Common Development Tasks\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("# Start all services (DB, Redis, MinIO)\n")
	sb.WriteString("docker compose up -d\n\n")
	sb.WriteString("# Run Go API\n")
	sb.WriteString("cd apps/api && air\n\n")
	if opts.ShouldIncludeWeb() {
		sb.WriteString("# Run web app\n")
		sb.WriteString("cd apps/web && pnpm dev\n\n")
	}
	if opts.ShouldIncludeAdmin() {
		sb.WriteString("# Run admin panel\n")
		sb.WriteString("cd apps/admin && pnpm dev\n\n")
	}
	sb.WriteString("# Run database migrations\n")
	sb.WriteString("cd apps/api && go run cmd/migrate/main.go\n\n")
	sb.WriteString("# Generate a new full-stack resource\n")
	sb.WriteString("jua generate resource Post title:string content:text published:bool\n\n")
	sb.WriteString("# Run tests\n")
	sb.WriteString("cd apps/api && go test ./... -race\n")
	sb.WriteString("```\n\n")

	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by `jua generate agents`. Update this file as the project evolves.*\n")

	return sb.String()
}
